name: PartnerMirror
options:
  minimumXcodeGenVersion: 2.0.0
targets:
  PartnerMirror:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - Sources
    settings:
      SWIFT_VERSION: 5.0
    info:
      path: Info.plist
      properties: {}
